import 'dart:convert';

import 'package:http/http.dart' as http;

class GeminiAPI{
  // create a header
  static Future<Map<String, String>> getHeader()async{
    return{
      'Content-Type' : 'application/json',
    };
  }

  // create a http request
  static Future<String> getGeminiData(message) async{
    try{
      final header = await getHeader();

      final Map<String, dynamic> requestBody = {
        'contents' : [
          {
            'parts' : [
              {
                'text' : 'user message request here $message'
              }
            ]
          }
        ],
        'generationConfig': {
          'temperature': 0.8, //it may from 0 to 1
          'maxOutputTokens': 1000 // its the max tokens to generate result
        }
      };

      String url = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=AIzaSyARVFVNCddMhCRlh_fH78d1he4dZKHidyk'; //

      //lets send request using above data
      //import http
      var response = await http.post(
        Uri.parse(url),
        headers: header,
        body: jsonEncode(requestBody),
      );

      print(response.body); //to fix if theres any error

      if(response.statusCode == 200){ //200 for success response
        var jsonResponse = jsonDecode(response.body) as Map<String, dynamic>;
        return jsonResponse['candidates'][0]['content']['parts'][0]['text'];
        //this return the result generated by gemini
      }else{
        return '';
      }

    }catch(e){
      print("Error: $e");
      return '';
    }
  }
}